### PR TITLE
Updates to the run()

### PR DESCRIPTION
**Pull request by markmcdowall**
Hi David,

A while back there was a change to the run() in the Tool API to the order of the parameters.

Was: `run(in_files, out_files, metadata)`
Now: `run(in_files, metadata, out_files)`

This is for both the Tool and Workflow definitions.

This branch includes the changes to convert the tools and the pipelines.

If the changes look fine to you and they are still viable then they can be merged into the tadbit_tools_update. At which point that can then get merged into master

Cheers,

Mark

### CODE REVIEW

**Comment by markmcdowall** [comment]
Hi David,

I have worked through the code for the pipelines and the tools, it should not be python 2 and 3 compliant, so should be ready for updates to TADbit.

Could you check through the changes, the key ones being the run() functions, but also there have been changes to use open() rather than file(). We also use the past.builtins module for handling the basestring as this was removed in the move from python 2 to 3.

If you could make sure that your tests are fine that would be great as I can then merge these and the tool_update changes down into the master branch.

Cheers,

Mark

**Comment by markmcdowall** [comment]
Excellent news, at least I have not broken anything for you running the code.

Would you like me to merge it on the tadbit_tools_update branch in that case?

Also for this week only we are having the normal Wednesday 15:00 CEST Skype call on Thursday at 15:00 if you are able to make it.

Cheers,

Mark

**Comment by markmcdowall** [comment]
Would you like the code merging down onto master as well?

**Comment by david-castillo** [comment]
Ok for me if you merge to master.

**Pull request merged**
