### PR TITLE
Rf i nps wrapper

### PR DESCRIPTION
**Pull request by rehamFatima**

### CODE REVIEW

**Comment by rehamFatima** [comment]
Pull request created

**Comment by markmcdowall** [comment]
Hi Reham,

Looks like there is an error in the code.

At the moment it just looks like an indentation error in the bs_seeker_filter.py module.

Cheers,

Mark

**Comment by rehamFatima** [comment]
bs_seeker_filter.py indentation error in the iNPS Wrapper ?

**Comment by markmcdowall** [comment]
Check the Travis output. It also looks like there are a few merge conflicts as well.

Cheers

**Pull request merged**
